import { Connection, Keypair, PublicKey } from '@solana/web3.js';
import { createMint, getOrCreateAssociatedTokenAccount, mintTo, approve, TOKEN_PROGRAM_ID } from '@solana/spl-token';
import { loadOrGenerateKeypair, requestAirdrop, DEVNET_URL, DATA_DIR } from './utils';
import fs from 'fs';
import path from 'path';
import bs58 from 'bs58';

async function setup() {
  console.log('🚀 Setting up x402 Facilitator Demo (Devnet)');
  console.log('============================================');
  console.log(`📂 Data directory: ${DATA_DIR}`);

  const connection = new Connection(DEVNET_URL, 'confirmed');

  // 1. Load/Generate Wallets
  const facilitator = loadOrGenerateKeypair('facilitator');
  const merchant = loadOrGenerateKeypair('merchant');
  const client = loadOrGenerateKeypair('client');
  const mintAuth = loadOrGenerateKeypair('mint_auth');

  console.log(`\n🔑 Wallets:`);
  console.log(`   Facilitator: ${facilitator.publicKey.toBase58()}`);
  console.log(`   Merchant:    ${merchant.publicKey.toBase58()}`);
  console.log(`   Client:      ${client.publicKey.toBase58()}`);

  // 2. Fund Wallets (SOL)
  console.log('\n💰 Checking SOL balances...');
  await requestAirdrop(connection, facilitator.publicKey);
  await requestAirdrop(connection, client.publicKey);
  // Merchant doesn't strictly need SOL to receive tokens, but good to have
  await requestAirdrop(connection, merchant.publicKey);
  await requestAirdrop(connection, mintAuth.publicKey);

  // 3. Create Mint (Simulating SBC Token)
  console.log('\ncoin Creating/Loading Token Mint...');
  let mintAddress: PublicKey;
  const mintPath = path.join(DATA_DIR, 'mint.json');
  
  // Reuse mint if exists to save time/complexity, or create new
  // For simplicity in this demo, we'll create a new one or load address if stored
  if (fs.existsSync(mintPath)) {
      mintAddress = new PublicKey(fs.readFileSync(mintPath, 'utf-8'));
      console.log(`   Using existing Mint: ${mintAddress.toBase58()}`);
  } else {
      mintAddress = await createMint(
        connection,
        mintAuth,
        mintAuth.publicKey,
        null,
        9
      );
      fs.writeFileSync(mintPath, mintAddress.toBase58());
      console.log(`   ✅ Created New Mint: ${mintAddress.toBase58()}`);
  }

  // 4. Setup Client Token Account & Mint Tokens
  console.log('\n👤 Setting up Client Token Account...');
  const clientATA = await getOrCreateAssociatedTokenAccount(
    connection,
    client,
    mintAddress,
    client.publicKey
  );
  console.log(`   Client ATA: ${clientATA.address.toBase58()}`);

  console.log('   Minting 100 SBC to Client...');
  await mintTo(
    connection,
    mintAuth,
    mintAddress,
    clientATA.address,
    mintAuth,
    100 * 1e9 // 100 tokens
  );
  console.log('   ✅ Minted 100 SBC');

  // 5. Setup Merchant Token Account (so it exists for receiving)
  console.log('\n🏪 Setting up Merchant Token Account...');
  const merchantATA = await getOrCreateAssociatedTokenAccount(
    connection,
    merchant, // payer (merchant pays for their own rent)
    mintAddress,
    merchant.publicKey
  );
  console.log(`   Merchant ATA: ${merchantATA.address.toBase58()}`);

  // 6. Approve Facilitator as Delegate (CRITICAL STEP for x402 Settlement)
  console.log('\n🤝 Approving Facilitator as Delegate...');
  // Check current delegate status? No, just re-approve for simplicity
  await approve(
      connection,
      client,                  // Payer
      clientATA.address,       // Account to delegate
      facilitator.publicKey,   // Delegate (Facilitator)
      client.publicKey,        // Owner
      1000 * 1e9               // Amount to approve (generous limit)
  );
  console.log('   ✅ Facilitator approved to spend up to 1000 SBC from Client');

  // 7. Generate .env file
  console.log('\n📝 Generating .env file for Facilitator...');
  const envContent = `
# Generated by demo/setup.ts
FACILITATOR_PORT=3001

# Solana Configuration (Devnet)
SOLANA_RPC_URL=${DEVNET_URL}
SOLANA_FACILITATOR_PRIVATE_KEY=${bs58.encode(facilitator.secretKey)}
SOLANA_FACILITATOR_ADDRESS=${facilitator.publicKey.toBase58()}
SOLANA_MERCHANT_ADDRESS=${merchant.publicKey.toBase58()}

# Token Configuration
SBC_TOKEN_ADDRESS=${mintAddress.toBase58()}

# Base Configuration (Not used in this demo, but required by config loader)
BASE_RPC_URL=https://sepolia.base.org
BASE_CHAIN_ID=84532
BASE_SBC_TOKEN_ADDRESS=0x0000000000000000000000000000000000000000
BASE_FACILITATOR_PRIVATE_KEY=0x0000000000000000000000000000000000000000000000000000000000000000
`.trim();

  fs.writeFileSync(path.join(process.cwd(), '.env'), envContent);
  console.log('   ✅ .env file created');

  console.log('\n🎉 Setup Complete!');
  console.log('   1. Start the server: npm run dev');
  console.log('   2. Run the demo client: npm run demo');
}

setup().catch(err => {
    console.error('❌ Setup failed:', err);
});
